scannerCSVsorter: scannerCSVsorter.c mergesort.o
	gcc scannerCSVsorter.c mergesort.o -o scannerCSVsorter

mergesort.o: mergesort.c
	gcc  -c mergesort.c -o mergesort.o
	
clean:
	rm -rf scannerCSVsorter mergesort.o
